"""create palettes and colors tables

Revision ID: 2ab6836227e8
Revises: 8f9112789f5c
Create Date: 2024-04-07 12:49:01.386384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ab6836227e8"
down_revision: Union[str, None] = "8f9112789f5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "palettes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "colors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column("hex_color", sa.String(length=32), nullable=False),
        sa.Column("palette_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["palette_id"],
            ["palettes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hex_color"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_table("colors")
    op.drop_table("palettes")
    # ### end Alembic commands ###
